### ISSUE TITLE
Reorganize page layout

### ISSUE THREAD

**Issue by miyehn** [xivintheshell/xivintheshell#36]
Maybe issues is a better dumping ground than PRs when something takes longer and needs multiple PRs. Anyway this is a continuation of #31.

### TODO

Right
- [x] add "level" to Overview
- [x] line height for Overview and Control tabs
- [x] show exact overrides in the overview tab

Bottom

- [x] Timeline markers
  * Columns "presets", "load/save", "add"
- [x] Import/Export
  - [x] Columns "fight export", "fight import", "image export"
  - [x] move the image export checkboxes to display settings (and apply them for general timeline canvas rendering)
  - [x] adjust multi-line image export canvas height & gap between lines

Misc
- [x] figure out one of the resizeable column modules and make a common component for it (or for now just a generic columns wrapper)
- [x] update instructions if needed
- [x] localization

**Comment by miyehn** [comment]
should be done after #42 gets in so closing this
